#ifndef CMAKE_DEFINES_HPP
#define CMAKE_DEFINES_HPP

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define COPYLEFT_NOTICE "@PROJECT_COPYLEFT@"

#endif//CMAKE_DEFINES_HPP