#ifndef PROJECT_MACROS_HPP
#define PROJECT_MACROS_HPP

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define COPYLEFT_NOTICE "@PROJECT_COPYLEFT@"

#endif//PROJECT_MACROS_HPP