#ifndef PROJECT_MACROS_HPP
#define PROJECT_MACROS_HPP

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VERSION "@PROJECT_VERSION@"
#define COPYLEFT_NOTICE "@PROJECT_COPYLEFT@"
#define GL_CONTEXT_VERSION_MAJOR @GL_CONTEXT_VERSION_MAJOR@
#define GL_CONTEXT_VERSION_MINOR @GL_CONTEXT_VERSION_MINOR@

#endif//PROJECT_MACROS_HPP